"""Write content/build_info.py: the git SHAs a build of the dashboard embeds.

The starlist schema has no field yet for the software that produced a
starlist, so until it does the dashboard stamps the two SHAs that matter
-- the pinned bandaid commit and this repo's own commit -- into every
``.star`` file name and into the zip name (`photom_dashboard.provenance_tag`).
Neither SHA is knowable from inside the kernel: bandaid has no tags, so its
hatch-vcs version string is not a reliable carrier, and browser-photom is
not a package at all. So the ``build-info`` pixi task runs this on the host,
after ``fetch-bandaid`` and before ``build``/``build-dash``, and the
generated module is copied into the kernel with the rest of content/. It is
gitignored: it describes a build, not the source.

Usage: ``python scripts/write_build_info.py [--repo DIR] [--bandaid DIR]
[--out FILE]``. A dirty checkout (tracked changes; untracked files ignored,
since the fetched clones live inside the repo) gets a ``-dirty`` suffix so a
starlist from a locally patched tree cannot pass for the committed one.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def git_sha(repo, *, short=7):
    """``<short sha>``, with ``-dirty`` appended when tracked files differ.

    Raises ``subprocess.CalledProcessError`` when ``repo`` is not a git
    checkout: a build that cannot say what it built should fail, not stamp
    the starlists with a placeholder.
    """
    repo = Path(repo)
    sha = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", f"--short={short}", "HEAD"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    status = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--untracked-files=no"],
        check=True, capture_output=True, text=True,
    ).stdout
    return f"{sha}-dirty" if status.strip() else sha


def render(bandaid_sha, browser_photom_sha):
    return (
        "# Generated by scripts/write_build_info.py (the `build-info` pixi task).\n"
        "# Describes one build; gitignored. Do not edit by hand.\n"
        f"BANDAID_SHA = {bandaid_sha!r}\n"
        f"BROWSER_PHOTOM_SHA = {browser_photom_sha!r}\n"
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", default=REPO_ROOT, type=Path,
                        help="browser-photom checkout (default: this repo)")
    parser.add_argument("--bandaid", default=REPO_ROOT / "bandaid-src", type=Path,
                        help="bandaid checkout (default: bandaid-src/)")
    parser.add_argument("--out", default=REPO_ROOT / "content" / "build_info.py",
                        type=Path, help="module to write")
    args = parser.parse_args(argv)

    bandaid_sha = git_sha(args.bandaid)
    browser_photom_sha = git_sha(args.repo)
    args.out.write_text(render(bandaid_sha, browser_photom_sha))
    print(f"{args.out}: bandaid {bandaid_sha}, browser-photom {browser_photom_sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
